/*
 * generated by Xtext 2.10.0
 */
package org.xtext.comp.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.comp.ui.internal.CompActivator;

public class WhUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CompActivator.getInstance().getInjector("org.xtext.comp.Wh");
	}

}
